# Start with a base image containing Java runtime
FROM openjdk:8

# Make port 8080 available to the world outside this container
EXPOSE 8080

ADD target/SpringBoot-Sonar-Docker.jar SpringBoot-Sonar-Docker.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/SpringBoot-Sonar-Docker.jar"]